rem see https://manual.calibre-ebook.com/creating_plugins.html#id14 goto Debugging plugins...
rem click runit from from the directory where the plugin is developed... 
rem this will kill any running calibre, push a new plugin.zip where appropriate and start calibre again in gui debug mode

calibre-debug -s
calibre-customize -b .
rem START calibre-debug --gui  creates a new cmd windows that executes calibre-debug --gui 
rem this allows killing a running calibre without fumbling all over the places on my too small monitor...
START calibre-debug --gui
